name: Server Test
on: push

jobs:
  lint:
    name: Server lint

    runs-on: ubuntu-latest
    env:
      go-version: 1.15.5

    steps:
      - uses: actions/checkout@v2
      # Note: golangci/golangci-lint-action caches. Should not use actions/cache@v2 otherwise result in so many "File exists"
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: generate
        shell: bash
        working-directory: server
        run: |
          go mod download
          make generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33.0
          working-directory: server
      - name: Other Lint
        shell: bash
        working-directory: server
        run: |
          make lint
      - name: Update Go Report Card
        if: github.ref == 'refs/heads/main'
        shell: bash
        working-directory: server
        run: curl -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks

  test:
    name: Server test

    runs-on: ubuntu-latest
    container: golang:1.15.5-buster
    services:
      redis:
        image: redis:6.0.9
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /go/pkg/mod  # Not ~/go/pkg/mod because "container" is active.
          key: ${{ runner.os }}-server-gomod-${{ hashFiles('server/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-server-gomod-
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        shell: bash
        working-directory: server
        run: |
          make test
        env:
          DSPS_REDIS: "redis:6379"
      - name: Upload to codecov
        if: github.ref == 'refs/heads/main'
        shell: bash
        working-directory: server
        run: |
          curl -s https://codecov.io/bash > codecov.sh
          bash codecov.sh
      - uses: actions/upload-artifact@v2
        with:
          name: coverage.html
          path: server/coverage.html
  
  build-test:
    name: Server Build

    runs-on: ubuntu-latest
    env:
      go-version: 1.15.5

    steps:
      - uses: actions/checkout@v2
      # Note: golangci/golangci-lint-action caches. Should not use actions/cache@v2 otherwise result in so many "File exists"
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: build
        shell: bash
        working-directory: server
        run: |
          go mod download
          make build
